#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
    herbstclient attr theme.title_when multiple_tabs


}

hc emit_hook reload

xsetroot -solid '#2b3338'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod1=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier


S_base02="#112"
#S_base03op="#002b36aa"
#S_base03="#002b36"
S_base03="#000"
#S_base02="#073642"
S_base02="#111"
S_base01="#586e75"
S_base00="#657b83"
S_base0="#839496"
S_base1="#93a1a1"
S_base2="#eee8d5"
S_base3="#fdf6e3"
S_yellow="#b58900"
S_orange="#cb4b16"
S_red="#dc322f"
S_magenta="#d33682"
S_violet="#6c71c4"
S_blue="#268bd2"
S_cyan="#2aa198"
S_green="#859900"

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn "${TERMINAL:-kitty}" # use your $TERMINAL with xterm as fallback

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Control-u       split   bottom  0.5
hc keybind $Mod-Control-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1,2,3,4,5,6,7,8,9,'a','b','c'} )
tag_keys=( {1,2,3,4,5,6,7,8,9,'d','u','b'} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Control-f tiling toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Control-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Control-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-Shift-m jumpto last-minimized
hc keybind $Mod-Control-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod1-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#2b3339'
hc set frame_border_normal_color '#2b3339'
hc set frame_bg_normal_color $S_base03op
hc set frame_bg_active_color $S_base03op
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent off
hc set frame_transparent_width 0
hc set frame_gap 0


# "#fe8019" "#d65d0e" "#af3a03'
hc attr theme.title_height 12
hc attr theme.title_when always
hc attr theme.title_font 'Mononoki Nerd Font:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3  # space below the title's baseline
hc attr theme.active.color $S_base03
hc attr theme.normal.color $S_base02
hc attr theme.title_color  $S_base2
hc attr theme.normal.color $S_base03
hc attr theme.urgent.color $S_red

hc attr theme.tab_color $S_base02
hc attr theme.normal.tab_color $S_base02
hc attr theme.active.tab_color $S_base02
hc attr theme.active.tab_outer_color $S_base02
hc attr theme.active.tab_title_color $S_base2

hc attr theme.normal.title_color $S_base3
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.fullscreen.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color $S_base01
hc attr theme.urgent.inner_color $S_magenta
hc attr theme.normal.inner_color $S_base02
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color $S_base02

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
hc pad 1 20
hc pad 0 20 

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done


hc keybind $Mod-p spawn rofi -show drun
hc keybind $Mod-Shift-s spawn flameshot gui
hc keybind $Mod-Shift-e spawn rofi -show emoji
#hc keybind $Mod-Shift-p spawn rofi-pass
#hc keybind $Mod-Shift-p spawn quickeepass ~/.password-store/Passwords.kdbx


# SCRATCHPADS
#hc keybind $Mod-u use_index "0"
#spawn ~/.config/herbstluftwm/scratchpad.sh "hlwmScratch1" "kitty --class=hlwmScratch1"
#hc keybind $Mod-d	use_index "2"

#spawn  ~/.config/herbstluftwm/scratchpad.sh "hlwmScratchemascratch" "emacs --name hlwmScratchemascratch --title hlwmScratchemascratch"
hc keybind $Mod-Shift-m		spawn  ~/.config/herbstluftwm/scratchpad.sh "hlwmScratchVolume" "kitty --class=hlwmScratchVolume -e pulsemixer"
#hc keybind $Mod-Shift-d		spawn  ~/.config/herbstluftwm/scratchpad.sh "obsidian" "~.local/bin/Obsidian.AppImage"
hc keybind $Mod1-Control-space	spawn  emacsclient --eval "(emacs-everywhere)"

# put this somewhere after 'hc unrule -F' line
hc rule instance~hlwmScratch.* floating=on floatplacement=center # float all instances which contains 'hlwmScratch'

#Change Language
hc keybind $Mod-space spawn  xkb-switch -n
#~/.config/herbstluftwm/changelang
hc keybind $Mod1-shift spawn ~/.config/herbstluftwm/changelang
hc keybind $Mod-F3 spawn ~/.config/herbstluftwm/nospanish.sh 
hc keybind $Mod-F4 spawn ~/.config/herbstluftwm/noenglish.sh 


# SERVICES 
syncthing &
picom &

# BAR
polybar &

#~/.config/herbstluftwm/bar | lemonbar  -n "herbstluftwm" -B $S_base03 -F $S_base3 -f "mononoki Nerd Font:style=Bold:size=9" &


# WALLPAPER

feh --bg-fill ~/Pictures/mushroom.jpg

# Monitors

xrandr --output eDP --auto
xrandr --output HDMI-A-0 --auto
xrandr --output HDMI-A-0 --above-of eDP
herbstclient detect_monitors
brightnessctl s 255


# SOUND 
pipewire &
pipewire-pulse &
syndaemon &

# KEYBOARD

setxkbmap us,ru 

# WACOM TABLET

xinput map-to-output "Wacom One by Wacom S Pen stylus" HDMI-A-0

