#!/bin/sh

#your toggl api token
res=$(curl -u $TOGGL_API_TOKEN:api_token \
  -X GET https://api.track.toggl.com/api/v8/time_entries/current)
echo $res

# desc=$(echo $res  | jq -r '.data .description')
# dur=$(echo $res  | jq -r '.data .duration')
# 
# echo $desc
# echo $dur
