#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#          

bspc config border_width         2

bspc config active_border_color "#44475a"
bspc config normal_border_color "#282a36"
bspc config focused_border_color "#ff5555"

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Startup

$HOME/.config/polybar/launch.sh
$HOME/Scripts/startup/touchpad.sh
$HOME/Scripts/startup/wifi.sh

picom &

setxkbmap -layout us,fi,ru
