#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0 '#'
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI1')
if [[ $my_laptop_external_monitor != *disconnected* ]]; then
    # xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --above eDP1
    enact --pos top
    bspc monitor HDMI1 -d 1 2 3 4 5 '#'
    bspc monitor eDP1  -d 6 7 8 9 0
    ~/.config/polybar/launch.sh duo
else 
    ~/.config/polybar/launch.sh duo
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0 '#'
fi
#          

bspc config border_width         3

bspc config active_border_color "#44475a"
bspc config normal_border_color "#282a36"
bspc config focused_border_color "#6272a4"

bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplaye2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a polybar state=sticky


#Startup
export MAIN_DISPLAY=eDP1
export SECOND_DISPLAY=HDMI1
export BINSCRIPTS=$HOME/.local/bin/


$HOME/scripts/startup/touchpad.sh &
$HOME/scripts/startup/wifi.sh &
#$HOME/scripts/startup/spotifyshit &
$HOME/.local/bin/fullscreen-daemon &
picom &
blueman-tray &

setxkbmap -layout us,fi,ru &
variety --next

# --- Scratchpads --- #
  # terminal dropdown
  bspc rule -a dropdown sticky=on state=floating hidden=on
  alacritty --class dropdown,dropdown -d 85 26 -e "tmux" &
  tmux new -s scratchpad
  echo "" > /tmp/dropdown


#  $HOME/scripts/startup/spotifyshit &
#  bspc rule -a Spotify sticky=on state=floating hidden=on
#  spotify
#  $HOME/scripts/startup/spotifyshit &


bspc() {
    echo $@ | grep -q " fullscreen" && touch /tmp/bspcblock
    /usr/local/bin/bspc $@
}

killall flameshot
